device_id: lamp
device_name: Lamp
device_type: lem_arm

led:
  pins:
    red: 17
    green: 27
    blue: 22
  pwm_frequency: 1000
  default_color:
    r: 255
    g: 180
    b: 120

arm:
  serial_port: "/dev/ttyACM0"
  baud_rate: 1000000
  motor_model: "sts3215"
  joints:
    shoulder_pan:
      servo_id: 1
    shoulder_lift:
      servo_id: 2
    elbow_flex:
      servo_id: 3
    wrist_flex:
      servo_id: 4
    wrist_roll:
      servo_id: 5
